spring:
  application:
    name: CommunityBackend
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Sihun0206
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: BPWOEw2Fhs30Bl5C9j8FofEM3jQzPCKx1v1kp/pFOPk=
  #Access Token
  access-expiration: 1800000
  #Refresh Token
  refresh-expiration: 604800000